### ISSUE TITLE
API Source Code

### ISSUE THREAD

**Issue by dimutch833** [Matix-Media/os-game-launcher#1]
Where is source code of api?

**Comment by Matix-Media** [comment]
The API is closed source. This is to prevent security issues.

**Comment by dimutch833** [comment]
but you say project is closed

**Comment by dimutch833** [comment]
but project is closed

**Comment by Matix-Media** [comment]
The API is not very complicated. It should not take long to recreate it.

**Comment by dimutch833** [comment]
![зображення](https://user-images.githubusercontent.com/48991276/104201605-9af86480-5432-11eb-8949-8befb6587e2b.png)
Yep its works

**Comment by dimutch833** [comment]
but its basic functions work

**Comment by dimutch833** [comment]
like login and game page

**Comment by dimutch833** [comment]
its mockup api

**Comment by Matix-Media** [comment]
I have to admit, one of the reason why I don't publish the API, is because it is very quick and dirty. It also relies on an completely unnecessary PHP Framework. If I were you, I would completely start from scratch in Node.js for the API.

**Comment by dimutch833** [comment]
> 
> 
> I have to admit, one of the reason why I don't publish the API, is because it is very quick and dirty. It also relies on an completely unnecessary PHP Framework. If I were you, I would completely start from scratch in Node.js for the API.

This is Node.js :)

**Comment by Matix-Media** [comment]
That's nice! So it doesn't make sense to give you the code, because it is a completely different language using completely different libraries.
